### ISSUE TITLE
Enhancement: Add a `drop_all` function

### ISSUE THREAD

**Issue by cofin** [litestar-org/advanced-alchemy#102]
### Summary

There should be a way to drop all current tables in your database including the `alembic_versioning` table.  This is really useful for rapid prototyping.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/102">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/102/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/102/pledge.svg">
</picture>
</a>

**Comment by tpougy** [comment]
This feature would be very useful
