### ISSUE TITLE
Bug(docs): Documentation changes cause Litestar docs to encounter buildtime errors

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/advanced-alchemy#142]
### Description

When building docs, changes in AA are sometimes causing Litestar build steps to warn/fail.

Solution would be to set up a CI workflow to check out the develop branch of Litestar and build the docs against the latest AA codebase, and fail if any build errors are encountered.

This way we can ensure (up?) downstream build success. 

### URL to code causing the issue

https://github.com/litestar-org/litestar/actions/runs/8206934469/job/22447123447?pr=3169

**Comment by cofin** [comment]
Closed by litestar-org/litestar#3169
