### ISSUE TITLE
Bug: Impossible to use unique() method for results after executing

### ISSUE THREAD

**Issue by Wh1teStr1pe** [litestar-org/advanced-alchemy#160]
### Description

**Description**
I am encountering a `sqlalchemy.exc.InvalidRequestError` when using `lazy='joined'` loading strategy across my models. The error states: "The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections." However, applying `unique()` is not feasible in my current implementation.
There is no way to make results unique() considering using lazy='joined'

### MCVE

```python
# Here you would put a simplified version of your code that still produces the error.
# For example:

from sqlalchemy.orm import joinedload
from myapp.models import Parent, Child

# Example query that leads to the error
session.execute(select(Parent).options(joinedload(Parent.children))).scalars()
```

### Jolt Project Version

0.0.9

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/160">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/160/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/160/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Can you edit your MCVE to be more representation of your issue? Right now I can not copy paste that to reproduce the bug you claim. For a start, can you add your models?

**Comment by ryou90** [comment]
Hi,
i m also run into this problem.

My example models:

```python
class Category(UUIDv7Base):
    name: Mapped[str50]
    descriptions: Mapped[list[CategoryDescription]] = relationship(
        back_populates="category",
        passive_deletes=True,
        lazy="selectin",
    )

class CategoryDescription(UUIDv7Base):
    name: Mapped[str]
    is_default: Mapped[bool] = Field(default=False)
    category_id: Mapped[UUID] = Field(ForeignKey("category.id"))
    category: Mapped[Category] = relationship(
        back_populates="descriptions", lazy="joined", innerjoin=True, viewonly=True
    )
```

My statement query in the provide depenendy function:

```python
async def provide_category_service(
    db_session: AsyncSession, request: Request
) -> AsyncGenerator[CategoryService, None]:
    statement = (
        select(Category)
        .join(Category.descriptions)
        .filter(
            (CategoryDescription.lang == "en")
            | (CategoryDescription.is_default == True)
        )
        .options(contains_eager(Category.descriptions))
        .execution_options(populate_existing=True)
    )

    async with CategoryService.new(session=db_session, statement=statement) as service:
        yield service

```

This returns the following error:
_"advanced_alchemy.exceptions.RepositoryError: An exception occurred: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections"_

**Comment by Wh1teStr1pe** [comment]
@ryou90 @Alc-Alc Same error, the problem is that it’s impossible to make scalar result unique

**Comment by Alc-Alc** [comment]
Here is a minimal example that reproduces this issue

```py
from advanced_alchemy.base import UUIDv7Base
from advanced_alchemy.repository import SQLAlchemySyncRepository
from sqlalchemy import ForeignKey, create_engine, select
from sqlalchemy.orm import Mapped, Session, contains_eager, mapped_column, relationship
from uuid_utils import UUID

class Category(UUIDv7Base):
    descriptions: Mapped[list["CategoryDescription"]] = relationship(
        back_populates="category", passive_deletes=True, lazy="selectin"
    )

class CategoryDescription(UUIDv7Base):
    name: Mapped[str]
    lang: Mapped[str]
    is_default: Mapped[bool] = mapped_column(default=False)
    category_id: Mapped[UUID] = mapped_column(ForeignKey("category.id"))
    category: Mapped[Category] = relationship(
        back_populates="descriptions", lazy="joined", innerjoin=True, viewonly=True
    )

engine = create_engine("sqlite:///db.sqlite")
UUIDv7Base.metadata.create_all(engine)

statement = (
    select(Category)
    .join(Category.descriptions)
    .filter(
        (CategoryDescription.lang == "en") | (CategoryDescription.is_default == True),
    )
    .options(contains_eager(Category.descriptions))
    .execution_options(populate_existing=True)
)

class CategoryRepository(SQLAlchemySyncRepository[Category]):
    model_type = Category

with Session(engine) as db_session:
    category = Category(
        descriptions=[
            CategoryDescription(name="name 1", lang="en", is_default=True),
            CategoryDescription(name="name 2", lang="en", is_default=True),
        ],
    )
    db_session.add(category)
    db_session.commit()
    repo = CategoryRepository(session=db_session, statement=statement)
    repo.get(category.id)
```

I will let @cofin comment more on what his suggestion is here 🙂

**Comment by cofin** [comment]
I feel like this is working as intended.  The reason you need `unique` here is because of the cardinality of the row.

When you execute this:

```python

statement = (
    select(Category)
    .join(Category.descriptions)
    .filter(
        (CategoryDescription.lang == "en") | (CategoryDescription.is_default == True),
    )
    .options(contains_eager(Category.descriptions))
    .execution_options(populate_existing=True)
)
```
You are joining to a table that has 1 to many relationship with Category.  When you have more than 1 description for a given category, this query returns 2 rows.

IMO, the fix here is to use the correct cardinality on the relationship.  It should be a `selectin` instead of a `joined` load.

**Comment by cofin** [comment]
OK, Actually after re-reviewing this and testing a few things, I see that was incorrect.  Give me a little time to test a few things out and get back on this.

**Comment by cofin** [comment]
Ok, take a look at this sample.  I believe this is the way I'd approach this:
```python
from advanced_alchemy.base import UUIDv7Base
from advanced_alchemy.repository import SQLAlchemySyncRepository
from sqlalchemy import ForeignKey, create_engine, select
from sqlalchemy.orm import Mapped, Session, mapped_column, relationship
from uuid_utils import UUID


class Category(UUIDv7Base):
    descriptions: Mapped[list["CategoryDescription"]] = relationship(
        back_populates="category",
        foreign_keys="CategoryDescription.category_id",
        passive_deletes=True,
        lazy="selectin",
    )


class CategoryDescription(UUIDv7Base):
    name: Mapped[str]
    lang: Mapped[str]
    is_default: Mapped[bool] = mapped_column(default=False)
    category_id: Mapped[UUID] = mapped_column(ForeignKey("category.id"))
    category: Mapped[Category] = relationship(
        back_populates="descriptions",
        lazy="joined",
        innerjoin=True,
        viewonly=True,
    )


engine = create_engine("sqlite:///:memmory/")
UUIDv7Base.metadata.create_all(engine)


class CategoryRepository(SQLAlchemySyncRepository[Category]):
    model_type = Category


with Session(engine) as db_session:
    category = Category(
        descriptions=[
            CategoryDescription(name="name 1", lang="en", is_default=True),
            CategoryDescription(name="name 2", lang="en", is_default=True),
        ],
    )
    db_session.add(category)
    db_session.commit()
    repo = CategoryRepository(session=db_session)
    count = repo.count()
    repo.get(category.id)
    _ = repo.list(
        Category.id.in_(
            select(CategoryDescription.category_id).where(
                CategoryDescription.lang == "en", CategoryDescription.is_default
            )
        ),
    )
    ```

**Comment by ryou90** [comment]
Hi,
thanks for your example.
But the solution is not quite correct. In your statement, the categories are selected based on the subqueries first. I.e. First select the CategoryDescriptions (where) and then the Categories accordingly.
But I want to select the Categories first and based on that, select  the CategoryDescriptions with a modified selectin query. 

> You are joining to a table that has 1 to many relationship with Category. When you have more than 1 description for a given category, this query returns 2 rows.

Correct, this is a one-to-many relationship. And in the normal case (without conditions) you can easily query this using sqlalchemy with _.options(selectinload(...))_

But since I want to use a custom selectin query, we must tell sqla via _contains_eager_ that we using a custom "joinquery".

This use case is also explicitly explained in the [documentation](https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html#using-contains-eager-to-load-a-custom-filtered-collection-result). In this case, unique() is therefore also required.

**Comment by cofin** [comment]
I am struggling to see how what I've provided doesn't do the same thing as the mcve.  Sure it's a slightly different query, but you can modify that accordingly.  The point is that you don't need `contains_eager` for this type of work. 

But to the original point of the post, as it currently sits, you can't use `contains_eager` on a statement in the repository when it returns a collection.  

I don't know when we'll be able to work something like this in, so my advice would be to refactor away from `contains_eager`.

**Comment by cofin** [comment]
Since I'm not sure how to best auto-detect whether the unique is needed, there is a simple solution you can use so that you aren't stuck.

This is an example of overriding the execute method of a repository and adding a `unique()` to the end.  Is this an OK solution for now?

```python
from __future__ import annotations

from typing import Any
from uuid import UUID  # noqa: TCH003

from sqlalchemy import ForeignKey, Result, Select, StatementLambdaElement, create_engine, select
from sqlalchemy.orm import Mapped, Session, contains_eager, mapped_column, relationship

from advanced_alchemy.base import UUIDv7Base
from advanced_alchemy.repository import SQLAlchemySyncRepository


class Category(UUIDv7Base):
    descriptions: Mapped[list[CategoryDescription]] = relationship(
        back_populates="category",
        foreign_keys="CategoryDescription.category_id",
        passive_deletes=True,
        lazy="selectin",
    )


class CategoryDescription(UUIDv7Base):
    name: Mapped[str]
    lang: Mapped[str]
    is_default: Mapped[bool] = mapped_column(default=False)
    category_id: Mapped[UUID] = mapped_column(ForeignKey("category.id"))
    category: Mapped[Category] = relationship(
        back_populates="descriptions",
        lazy="joined",
        innerjoin=True,
        viewonly=True,
    )


engine = create_engine("sqlite:///:memory:")
UUIDv7Base.metadata.create_all(engine)

statement = (
    select(Category)
    .join(CategoryDescription, onclause=Category.id == CategoryDescription.category_id)
    .where(CategoryDescription.lang == "en")
    .options(contains_eager(Category.descriptions))
    .execution_options(populate_existing=True)
)


class CategoryRepository(SQLAlchemySyncRepository[Category]):
    model_type = Category

    def _execute(self, statement: Select[Any] | StatementLambdaElement) -> Result[Any]:
        return self.session.execute(statement).unique()


with Session(engine) as db_session:
    category = Category(
        descriptions=[
            CategoryDescription(name="name 1", lang="en", is_default=True),
            CategoryDescription(name="name 2", lang="en", is_default=True),
        ],
    )
    db_session.add(category)
    db_session.commit()
    repo = CategoryRepository(session=db_session, statement=statement)
    count = repo.count()
    repo.get(category.id)

```
