### ISSUE TITLE
Bug: Repository initialization failing when passing execute_options argument

### ISSUE THREAD

**Issue by harteros** [litestar-org/advanced-alchemy#202]
### Description

After updating to the latest version the newly introduced `execution_options` variable of the repository throws an `InvalidRequestError` when providing the variable during the Repository initialization. This issue occurs on both Sync and Async repositories.

The problem occurs from the lambda statement and i found out that it can be fixed by simply setting the `track_bound_values=False` and `enable_tracking=False` ( [here](https://github.com/litestar-org/advanced-alchemy/blob/main/advanced_alchemy/repository/_async.py#L108-L111) and [here](https://github.com/litestar-org/advanced-alchemy/blob/main/advanced_alchemy/repository/_sync.py#L109-L112)) on the lambda statement during the repository initialization. 

This issue does not occur on the repository functions (e.g. `get` etc) as during those the `_get_base_statement` [function](https://github.com/litestar-org/advanced-alchemy/blob/main/advanced_alchemy/repository/_sync.py#L393) correctly sets the tracking variables to `false`

I would be more than happy to contribute and open a PR to address this

### MCVE

```python
from advanced_alchemy.base import UUIDBase
from advanced_alchemy.repository import SQLAlchemySyncRepository
from sqlalchemy import create_engine
from sqlalchemy.orm import Mapped, Session, sessionmaker

# Note that the same applies also to SQLAlchemyAsyncRepository

class User(UUIDBase):
    name: Mapped[str]


class UserRepository(SQLAlchemySyncRepository[User]):
    model_type = User


engine = create_engine("sqlite:///:memory:")
session_factory: sessionmaker[Session] = sessionmaker(engine, expire_on_commit=False)

with engine.begin() as conn:
    User.metadata.create_all(conn)

with session_factory() as session:
    repository = UserRepository(session=session, execution_options={"populate_existing": True})
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Logs

```bash
sqlalchemy.exc.InvalidRequestError: Can't invoke Python callable keys() inside of lambda expression argument at <code object <lambda> at 0x1036c26b0, file /lib/python3.11/site-packages/advanced_alchemy/repository/_sync.py", line 110>; lambda SQL constructs should not invoke functions from closure variables to produce literal values since the lambda SQL system normally extracts bound values without actually invoking the lambda or any functions within it.  Call the function outside of the lambda and assign to a local variable that is used in the lambda as a closure variable, or set track_bound_values=False if the return value of this function is used in some other way other than a SQL bound value.
```

### Package Version

v0.11.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
We don't want to disable caching completely because that impacts subsequent calls to that repository object.  

However, I think the fix in main will indirectly handle this as well.

**Comment by harteros** [comment]
Yeap i checked your latest release it is indeed fixed, thanks 🎉
