### ISSUE TITLE
Bug: Possibly missing 'order_by' during repo initialization for SQLAlchemyAsyncRepositoryReadService

### ISSUE THREAD

**Issue by Rey092** [litestar-org/advanced-alchemy#239]
https://github.com/litestar-org/advanced-alchemy/blob/48cdbd36fe16358b96fbc95fbc0bd7369f6d8fd6/advanced_alchemy/service/_async.py#L107C9-L107C17

I do not get it. Why do we get 'order_by', but not pass it to repository?

**Comment by cofin** [comment]
@Rey092 Thanks for posting this.  This is a bug and will be fixed in the upcoming release.
