### ISSUE TITLE
Bug: Typing issues in ModelDictT

### ISSUE THREAD

**Issue by vikigenius** [litestar-org/advanced-alchemy#265]
### Description

pyright complains when I try to assign `DTOData[User]` to `ModelDictT[User]`

```
/home/void/Projects/Python/litestartest/src/litestartest/controller.py
  /home/void/Projects/Python/litestartest/src/litestartest/controller.py:35:45 - error: Argument of type "DTOData[User]" cannot be assigned to parameter "data" of type "ModelDictT[User]" in function "create"
    Type "DTOData[User]" is incompatible with type "ModelDictT[User]"
      "DTOData[User]" is incompatible with "Dict[str, Any]"
      "DTOData[User]" is incompatible with "User"
      "DTOData[User]" is incompatible with "Struct"
      "DTOData[User]" is incompatible with protocol "Struct"
        "__struct_fields__" is not present
      "DTOData[User]" is incompatible with "BaseModel"
      "DTOData[User]" is incompatible with protocol "BaseModel"
    ... (reportArgumentType)
1 error, 0 warnings, 0 informations
```
You can't really see the error because pyright is supressing the last lines. But if I remove BaseModel from one of the union types you cans see the actual error

```
      "litestar.dto.data_structures.DTOData" is incompatible with "advanced_alchemy.service.typing.DTOData" (reportArgumentType)
```

You usually can't reproduce this error until you install pydantic. Because without pydantic installed in strict mode

you get

```
  /home/void/Projects/Python/litestartest/src/litestartest/service.py:10:42 - error: Type of "ModelDictT" is partially unknown
    Type of "ModelDictT" is "type[Dict[str, Any]] | type[ModelT@ModelDictT] | type[msgspec.Struct] | type[advanced_alchemy.service.typing.Struct] | Unknown | type[BaseModel] | type[DTOData[ModelT@ModelDictT]]" (reportUnknownVariableType)
```

Which suppresses the other issue.

I think in general the way ModelDictT is typed with try except does not actually seem to work properly.

### URL to code causing the issue

https://github.com/vikigenius/litestartest/tree/main

### Steps to reproduce

Run pyright or basedpyright on repository
Verify that `reportUnknownVariableType` is being produced in strict mode (because pydantic is not installed).

Install pydantic

Run pyright or basedpyright again.

This should cause the

```
/home/void/Projects/Python/litestartest/src/litestartest/controller.py
  /home/void/Projects/Python/litestartest/src/litestartest/controller.py:35:45 - error: Argument of type "DTOData[User]" cannot be assigned to parameter "data" of type "ModelDictT[User]" in function "create"
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Package Version

0.20.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
Closed by #277
