### ISSUE TITLE
Enhancement: Add Quart

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/advanced-alchemy#28]
### Summary

Quart is Flask made async: https://quart.palletsprojects.com/en/latest/

Wondering if there is any interest in adding it as a potential target?

### Drawbacks and Impact

More development maintenance

### Unresolved questions

What other targets could we add?

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/28">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/28/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/28/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Let's re-open this if the ask comes up.
